//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1022
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWeb.SrvUV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvUV.ServiceUVSoap")]
    public interface ServiceUVSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SiteWeb.SrvUV.HelloWorldResponse HelloWorld(SiteWeb.SrvUV.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément InfoFormationResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoFormation", ReplyAction="*")]
        SiteWeb.SrvUV.InfoFormationResponse InfoFormation(SiteWeb.SrvUV.InfoFormationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SiteWeb.SrvUV.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SiteWeb.SrvUV.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SiteWeb.SrvUV.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SiteWeb.SrvUV.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfoFormationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfoFormation", Namespace="http://tempuri.org/", Order=0)]
        public SiteWeb.SrvUV.InfoFormationRequestBody Body;
        
        public InfoFormationRequest() {
        }
        
        public InfoFormationRequest(SiteWeb.SrvUV.InfoFormationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoFormationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numF;
        
        public InfoFormationRequestBody() {
        }
        
        public InfoFormationRequestBody(int numF) {
            this.numF = numF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfoFormationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfoFormationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SiteWeb.SrvUV.InfoFormationResponseBody Body;
        
        public InfoFormationResponse() {
        }
        
        public InfoFormationResponse(SiteWeb.SrvUV.InfoFormationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoFormationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InfoFormationResult;
        
        public InfoFormationResponseBody() {
        }
        
        public InfoFormationResponseBody(string InfoFormationResult) {
            this.InfoFormationResult = InfoFormationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceUVSoapChannel : SiteWeb.SrvUV.ServiceUVSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUVSoapClient : System.ServiceModel.ClientBase<SiteWeb.SrvUV.ServiceUVSoap>, SiteWeb.SrvUV.ServiceUVSoap {
        
        public ServiceUVSoapClient() {
        }
        
        public ServiceUVSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUVSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUVSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUVSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiteWeb.SrvUV.HelloWorldResponse SiteWeb.SrvUV.ServiceUVSoap.HelloWorld(SiteWeb.SrvUV.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SiteWeb.SrvUV.HelloWorldRequest inValue = new SiteWeb.SrvUV.HelloWorldRequest();
            inValue.Body = new SiteWeb.SrvUV.HelloWorldRequestBody();
            SiteWeb.SrvUV.HelloWorldResponse retVal = ((SiteWeb.SrvUV.ServiceUVSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiteWeb.SrvUV.InfoFormationResponse SiteWeb.SrvUV.ServiceUVSoap.InfoFormation(SiteWeb.SrvUV.InfoFormationRequest request) {
            return base.Channel.InfoFormation(request);
        }
        
        public string InfoFormation(int numF) {
            SiteWeb.SrvUV.InfoFormationRequest inValue = new SiteWeb.SrvUV.InfoFormationRequest();
            inValue.Body = new SiteWeb.SrvUV.InfoFormationRequestBody();
            inValue.Body.numF = numF;
            SiteWeb.SrvUV.InfoFormationResponse retVal = ((SiteWeb.SrvUV.ServiceUVSoap)(this)).InfoFormation(inValue);
            return retVal.Body.InfoFormationResult;
        }
    }
}
